import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { spawnSync } from 'node:child_process'
import { writeFileSync, readFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const root = here
const outDir = join(root, 'src', 'generated')
const outFile = join(outDir, 'version.ts')

function readGit(args: string[]): string {
  try {
    return spawnSync('git', args, { cwd: root, encoding: 'utf8' }).stdout.trim()
  } catch {
    return ''
  }
}

function writeVersionFile() {
  const baseVersion = '2.0'
  const short = readGit(['rev-parse', '--short', 'HEAD'])
  const status = readGit(['status', '--porcelain'])
  const branch = readGit(['rev-parse', '--abbrev-ref', 'HEAD'])

  let tag = short ? `${baseVersion}-${short}` : baseVersion
  if (status) tag += '-dirty'

  const generated = `// Auto-generated by vite.config.ts. Do not edit.
export const APP_VERSION: string = ${JSON.stringify(tag)};
export const APP_BRANCH: string = ${JSON.stringify(branch)};
`

  mkdirSync(outDir, { recursive: true })
  let previous = ''
  try { previous = readFileSync(outFile, 'utf8') } catch { /* missing is fine */ }
  if (previous !== generated) writeFileSync(outFile, generated, 'utf8')
}

function ensureVersion() {
  return {
    name: 'sabotetris-version',
    buildStart() { writeVersionFile() },
    configureServer() { writeVersionFile() },
  }
}

// https://vite.dev/config/
export default defineConfig({
  plugins: [ensureVersion(), react()],
  base: '/sabotetris/',
})
