import { execFileSync } from 'node:child_process';
import { writeFileSync, readFileSync, mkdirSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, '..');
const outDir = join(root, 'src', 'generated');
const outFile = join(outDir, 'version.ts');

function safeExec(args) {
  try {
    return execFileSync('git', args, { cwd: root, encoding: 'utf8' }).trim();
  } catch {
    return '';
  }
}

const baseVersion = '2.0';
const short = safeExec(['rev-parse', '--short', 'HEAD']);
const status = safeExec(['status', '--porcelain']);
const branch = safeExec(['rev-parse', '--abbrev-ref', 'HEAD']);

let tag = short ? `${baseVersion}-${short}` : baseVersion;
if (status) tag += '-dirty';

const generated = `// Auto-generated by scripts/version.mjs. Do not edit.
export const APP_VERSION: string = ${JSON.stringify(tag)};
export const APP_BRANCH: string = ${JSON.stringify(branch)};
`;

mkdirSync(outDir, { recursive: true });
let previous = '';
try { previous = readFileSync(outFile, 'utf8'); } catch { /* missing is fine */ }
if (previous !== generated) writeFileSync(outFile, generated, 'utf8');
process.stdout.write(`version: ${tag}\n`);
